// export default {
//   login: 'john-smilga',
//   id: 42133389,
//   node_id: 'MDQ6VXNlcjQyMTMzMzg5',
//   avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
//   gravatar_id: '',
//   url: 'https://api.github.com/users/john-smilga',
//   html_url: 'https://github.com/john-smilga',
//   followers_url: 'https://api.github.com/users/john-smilga/followers',
//   following_url:
//     'https://api.github.com/users/john-smilga/following{/other_user}',
//   gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
//   starred_url:
//     'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
//   subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
//   organizations_url: 'https://api.github.com/users/john-smilga/orgs',
//   repos_url: 'https://api.github.com/users/john-smilga/repos',
//   events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
//   received_events_url:
//     'https://api.github.com/users/john-smilga/received_events',
//   type: 'User',
//   site_admin: false,
//   name: 'John Smilga',
//   company: 'Coding Addict',
//   blog: 'www.johnsmilga.com',
//   location: 'Los Angeles',
//   email: null,
//   hireable: null,
//   bio: 'Creator of Coding Addict',
//   twitter_username: 'john_smilga',
//   public_repos: 152,
//   public_gists: 0,
//   followers: 1495,
//   following: 0,
//   created_at: '2018-08-06T06:48:23Z',
//   updated_at: '2020-07-08T05:01:32Z',
// };

export default {
  login: 'adyeetya',
  id: 96496561,
  node_id: 'U_kgDOBcBrsQ',
  avatar_url: 'https://avatars.githubusercontent.com/u/96496561?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/adyeetya',
  html_url: 'https://github.com/adyeetya',
  followers_url: 'https://api.github.com/users/adyeetya/followers',
  following_url: 'https://api.github.com/users/adyeetya/following{/other_user}',
  gists_url: 'https://api.github.com/users/adyeetya/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/adyeetya/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/adyeetya/subscriptions',
  organizations_url: 'https://api.github.com/users/adyeetya/orgs',
  repos_url: 'https://api.github.com/users/adyeetya/repos',
  events_url: 'https://api.github.com/users/adyeetya/events{/privacy}',
  received_events_url: 'https://api.github.com/users/adyeetya/received_events',
  type: 'User',
  site_admin: false,
  name: 'Aditya Singh',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: true,
  bio: 'I am Aditya Singh Full Stack Web Developer, and Btech CSE Pre Final year student.',
  twitter_username: null,
  public_repos: 10,
  public_gists: 0,
  followers: 0,
  following: 2,
  created_at: '2021-12-21T19:14:02Z',
  updated_at: '2023-10-23T07:52:49Z',
} 
